name: Send Pet Notifications

on:
  schedule:
    - cron: '0 */2 * * *' # Запуск каждые 2 часа
  workflow_dispatch:      # Кнопка для ручного запуска

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install pyTelegramBotAPI firebase-admin

      - name: Run notification script
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          FIREBASE_JSON: ${{ secrets.FIREBASE_JSON }}
        run: python bot_notify.py